name: small_batch_cifar

defaults:
  - data: CIFAR100
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_
model: ConvNet

user:
  provide_labels: False
  num_data_points: 4

# Server and user:
num_queries: 1
